{% set version = '2.01-40' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-splancs
  version: {{ version|replace("-", "_") }}

source:
  fn: splancs_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/splancs_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/splancs/splancs_{{ version }}.tar.gz
  sha256: 79744381ebc4a361740a36dca3c9fca9ae015cfe0bd585b7856a664a3da74363

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-sp >=0.9
  run:
    - r-base
    - r-sp >=0.9

test:
  commands:
    - $R -e "library('splancs')"  # [not win]
    - "\"%R%\" -e \"library('splancs')\""  # [win]

about:
  home: http://www.maths.lancs.ac.uk/~rowlings/Splancs/
  license: GPL (>= 2)
  summary: 'The Splancs package was written as an enhancement to S-Plus for display and analysis
    of spatial point pattern data; it has been ported to R and is in "maintenance mode". '

  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
