appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: WzoGGDioO2n0prWDoHXfhOkJdaWADvH2EK2j13yJEZjtg8a0KtV0HIvE7WJx21HdwR8nl/iUxMJ0A0aj73j4eSUuwQPEXP4tUXw6WKVvOPn9NTHBtnOQDIDkTDyp63u2qSnx0vcziUYd+CTnGORE7YOsjjvDpAs1DC97wQ3rH+ReOebE8TweSmRhuFp5cs7lg1OGy9wg2DAXFl+POXMz6p5BKghTvfozYKzl6lFJVhV2VuTSNZHJuTeh6PbOpbCpXFjxfwzG+iq/8+WMoteLmFLwSbjMpts/aJbvMYCUzV9S1k1ztWiinvvXATHtBsR3HrfDCTCtdU1jwryORH9NRVlfmN/9dNDMw0T0N8bbF5RSg5eUUPOR72aDIWWWrtpaGqkp1wC3ln4MwOBLuiPSnPeEC2xeEYy7QbLIH5cg2ywEpL6X8LMeE9hqtr1bu0HFeQV5vlAurqr+IKxTEpIx+D/rsG5KTVQapsTeHpj7CQCpZXOA56+98JM9FdYzxqVBq6gVLFPA77N2FM2HFPZgfVc1Vypk36FU+7RtpkSPEuBbEQthy1+dzNpWMZwfyJwRtBP7Q9l0KedFoJktXu/DBPUufXhrTXR6zmKrehlENyGsR13CfyjkjQnd/tHFxPuu8r84qWdAxe9dZLbnqyAvKk2bGZtKdUvy/aZkxzEQAFI=
conda_forge_output_validation: true
